# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161017165332 on 2016-11-12 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepointer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralfilestore',
            name='recipients',
            field=models.CharField(default='[]', max_length=300),
        ),
        migrations.AlterField(
            model_name='centralfilestore',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
