# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161017165332 on 2016-11-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepointer', '0002_auto_20161112_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralfilestore',
            name='file_name',
            field=models.CharField(max_length=2),
        ),
    ]
