# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161017165332 on 2016-11-12 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharepointer', '0004_auto_20161112_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralfilestore',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
